#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper]
#+TITLE: Práctica Pig
#+AUTHOR: Alejandro Alcalde
#+LANGUAGE: es
#+LATEX_COMPILER: xelatex
#+STARTUP: inlineimages
#+STARTUP: latexpreview
#+OPTIONS: H:6

* Base de datos

La base de datos seleccionada es [[https://data.medicare.gov/Hospital-Compare/Complications-and-Deaths-Hospital/ynj2-r877][Complications-and-Deaths-Hospital]], una base de datos que recoge muertes en hospitales por distintas complicaciones tras una operación. Contiene 92.000 instancias y 19 columnas.

* Preparando el entorno

Antes de comenzar, es necesario crear los directorios necesarios:

#+BEGIN_SRC bash :tangle yes
hdfs dfs -mkdir practica
#+END_SRC

Posteriormente, se cargan los datos en hadoop:

#+BEGIN_SRC bash :tangle yes
hdfs dfs -put ~/Downloads/hospital.csv /practica
#+END_SRC

Hecho esto, se puede comprobar que se ha cargado correctamente con:

#+BEGIN_SRC bash :tangle yes
hdfs dfs -ls /practica
#+END_SRC

Una vez configurado todo, se crea la tabla que almacenará los datos del fichero:

#+BEGIN_SRC sql :tangle yes
REGISTER '/usr/lib/pig/piggybank.jar' ;
DEFINE CSVLoader org.apache.pig.piggybank.storage.CSVLoader();

hospital = LOAD 'practica/hospital.csv'
         USING CSVLoader AS (
            ProviderID: int,
            HospitalName: chararray,
            Address: chararray,
            City: chararray,
            State: chararray,
            ZIPCode: int,
            CountyName: chararray,
            PhoneNumber: chararray,
            MeasureName: chararray,
            MeasureID: chararray,
            ComparedtoNational: chararray,
            Denominator: int
         );
#+END_SRC

Para comprobar la correcta carga:

#+BEGIN_SRC sql :tangle yes
  describe hospital;
  hospital: {
            ProviderID: int,
            HospitalName: chararray,
            Address: chararray,
            City: chararray,
            State: chararray,
            ZIPCode: int,
            CountyName: chararray,
            PhoneNumber: chararray,
            MeasureName: chararray,
            MeasureID: chararray,
            ComparedtoNational: chararray,
            Denominator: int}
  grunt>
#+END_SRC

* Análisis de datos

En este análisis se quiere saber en qué estados suele haber muertes por complicaciones según el tipo de enfermedad y cómo se relaciona con la media del resto del país. Se plantean la siguiente cuestión:

- ¿En qué estados hay más complicaciones de Heart failure (HF)?

Primero se echa un vistazo preliminar a los datos, se muestran en el documento solo los 10 primeros:

#+BEGIN_SRC sql :tangle yes
A = FOREACH hospital GENERATE HospitalName, State PARALLEL 12;
B = LIMIT A 10;
DUMP B;

-- (COX MEDICAL CENTERS,MO)
-- (MERCY HOSPITAL LEBANON,MO)
-- (MERCY HOSPITAL LEBANON,MO)
-- (RESEARCH MEDICAL CENTER,MO)
-- (ST JOSEPH MEDICAL CENTER,MO)
-- (MERCY HOSPITAL WASHINGTON,MO)
-- (MERCY HOSPITAL SPRINGFIELD,MO)
-- (BATES COUNTY MEMORIAL HOSPITAL,MO)
-- (SSM HEALTH ST CLARE HOSPITAL - FENTON,MO)
-- (SSM HEALTH ST. MARY'S HOSPITAL-AUDRAIN,MO)
#+END_SRC

** Fallo cardíaco tras operación

Con esta consulta se seleccionan los hospitales y el estado al que pertenecen en los que los pacientes que han muerto a causa de un fallo cardíaco tras una operación. Además, en estos hospitales/estados, la media de este tipo de muerte es la peor con respecto al resto del país.

#+BEGIN_SRC sql :tangle yes
W = FILTER hospital BY (LOWER(MeasureName) matches '.*hf.*')
        AND (LOWER(ComparedtoNational) matches '.*worse.*')
         PARALLEL 12;
DUMP W;

-- (10005,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,2565938310,Heart failure (HF) 30-Day Mortality Rate,MORT_30_HF,Worse than the National Rate,349)
-- (260078,OZARKS MEDICAL CENTER,1100 KENTUCKY AVE,WEST PLAINS,MO,65775,HOWELL,4172569111,Heart failure (HF) 30-Day Mortality Rate,MORT_30_HF,Worse than the National Rate,204)
-- (260119,POPLAR BLUFF REGIONAL MEDICAL CENTER,3100 OAK GROVE ROAD,POPLAR BLUFF,MO,63901,BUTLER,5737857721,Heart failure (HF) 30-Day Mortality Rate,MORT_30_HF,Worse than the National Rate,454)
-- (260110,SOUTHEASTHEALTH,1701 LACEY ST,CAPE GIRARDEAU,MO,63701,CAPE GIRARDEAU,5733344822,Heart failure (HF) 30-Day Mortality Rate,MORT_30_HF,Worse than the National Rate,383)
-- (270049,ST VINCENT HEALTHCARE,1233 N 30TH ST,BILLINGS,MT,59101,YELLOWSTONE,4066577000,Heart failure (HF) 30-Day Mortality Rate,MORT_30_HF,Worse than the National Rate,346)
-- (280003,BRYAN MEDICAL CENTER,1600 SOUTH 48TH ST,LINCOLN,NE,68506,LANCASTER,4024811111,Heart failure (HF) 30-Day Mortality Rate,MORT_30_HF,Worse than the National Rate,642)
-- (280077,FREMONT HEALTH MEDICAL CENTER,450 EAST 23RD ST,FREMONT,NE,68025,DODGE,4027211610,Heart failure (HF) 30-Day Mortality Rate,MORT_30_HF,Worse than the National Rate,169)
-- (290001,RENOWN REGIONAL MEDICAL CENTER,1155 MILL STREET,RENO,NV,89502,WASHOE,7759824100,Heart failure (HF) 30-Day Mortality Rate,MORT_30_HF,Worse than the National Rate,453)
-- (300001,CONCORD HOSPITAL,250 PLEASANT ST,CONCORD,NH,3301,MERRIMACK,6032252711,Heart failure (HF) 30-Day Mortality Rate,MORT_30_HF,Worse than the National Rate,645)
#+END_SRC

Podemos agrupar para conocer en qué estados ocurre más veces este tipo de muerte:

#+BEGIN_SRC sql :tangle yes
A = FOREACH W GENERATE HospitalName, State, MeasureName PARALLEL 12;
B = GROUP A BY State PARALLEL 12;
C = FOREACH B GENERATE group, COUNT(A) AS NCases PARALLEL 12;
D = ORDER C BY NCases DESC;
DUMP D;

-- (AR,7)
-- (IL,6)
-- (FL,6)
-- (CA,5)
-- (IA,5)
-- (NY,5)
-- (MO,4)
-- (WI,4)
-- (IN,4)
-- (WA,4)
-- (AL,3)
-- (OK,3)
-- (KS,3)
-- (NC,3)
-- (TN,3)
-- (MI,3)
-- (PA,3)
-- (NV,2)
-- (TX,2)
-- (WY,2)
-- (VT,2)
-- (KY,2)
-- (SC,2)
-- (OR,2)
-- (NE,2)
-- (OH,2)
-- (WV,1)
-- (MS,1)
-- (VA,1)
-- (ME,1)
-- (ID,1)
-- (NH,1)
-- (PR,1)
-- (CT,1)
-- (CO,1)
-- (MT,1)
-- (NM,1)
#+END_SRC

Parece que en el estado AR (Arkansas), es donde más pacientes mueren por un fallo cardíaco tras ser operados, aunque pueda ser algo alto, quizá sea debido a que el 20% de la población de Arkansas tiene más de 65 años[fn:1]. Los otros dos estados con 6 muertes son Ilinóis y Florida, ambos también con un porcentaje de personas con más de 65 años algo alto (15% y 16% respectivamente). Sin embargo, mirando a uno de los estados con menos muertes (CT, Connecticut) el porcentaje de mayores también está entorno al 16%, por tanto quizá cabe pensar que influye el número de habitantes del estado. Florida tiene 20 millones de habitantes, mientras que Connecticut 3.5 millones. Si se muestran este tipo de muertes agrupando por el nombre del hospital, se observa que en ningún hospital ha ocurrido en más de una ocasión, con lo cual puede conlcuirse que son casos aislados:

* Footnotes

[fn:1] Datos obtenidos de https://www.census.gov/quickfacts/fact/table/FL/PST045217
